let students = [
  {
    name: "Abdikadir Samatar (Mac)",
    group: "App Dev Team",
    github: "https://github.com/abdikadirsamatar",
    linkedin: "https://www.linkedin.com/in/abdikadirsamatar/",
    email: "asamatar@appdev.yearup.org",
    nickname: "Mac Innovator",
    imageurl: "img/Avatar_Abdikadir.jpg",
    gender: "male",
  },
  {
    name: "Dante 'Donny' Angerame",
    group: "App Dev Team",
    github: "https://github.com/DanteAngerame",
    linkedin: "https://www.linkedin.com/in/danteangerame/",
    email: "dangerame@appdev.yearup.org",
    nickname: "Donny Developer",
    imageurl: "img/Avatar_Dante.jpg",
    gender: "male",
  },
  {
    name: "Guadalupe Argumedo Saucedo",
    group: "App Dev Team",
    github: "https://github.com/GuadalupeArgumedoSaucedo",
    linkedin: "https://www.linkedin.com/in/guadalupeargumedo/",
    email: "gargumedosaucedo@appdev.yearup.org",
    nickname: "Lupe Logic",
    imageurl: "img/Avatar_Guadalupe.jpg",
    gender: "female",
  },
  {
    name: "Jaranesca Braker (Mac)",
    group: "App Dev Team",
    github: "https://github.com/jaranesca",
    linkedin: "https://www.linkedin.com/in/jaranesca/",
    email: "jbraker@appdev.yearup.org",
    nickname: "Breakthrough",
    imageurl: "img/Avatar_Jaranesca.jpg",
    gender: "female",
  },
  {
    name: "Jesús Mimila (Mac)",
    group: "App Dev Team",
    github: "https://github.com/JesusMimilaHurtado",
    linkedin: "https://www.linkedin.com/in/jesusmimila/",
    email: "jmimila@appdev.yearup.org",
    nickname: "Jesús Jumps",
    imageurl: "img/Avatar_Jesus.jpg",
    gender: "male",
  },
  {
    name: "Kaaliyah Gray (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaaliyahGray",
    linkedin: "https://www.linkedin.com/in/kaaliyahgray/",
    email: "kgray@appdev.yearup.org",
    nickname: "Kaleidoscope",
    imageurl: "img/Avatar_Kaaliyah.jpg",
    gender: "female",
  },
  {
    name: "Kadiatou Barry (Mac)",
    group: "App Dev Team",
    github: "https://github.com/kadylius/kadi-barry",
    linkedin: "https://www.linkedin.com/in/kadiatoubarry/",
    email: "kbarry@appdev.yearup.org",
    nickname: "Kadi Catalyst",
    imageurl: "img/Avatar_Kadiatou.jpg",
    gender: "female",
  },
  {
    name: "Kayla Hanifen (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaylaEHanifen",
    linkedin: "https://www.linkedin.com/in/kaylahanifen/",
    email: "khanifen@appdev.yearup.org",
    nickname: "Hanifen Helper",
    imageurl: "img/Avatar_Kayla.jpg",
    gender: "female",
  },
  {
    name: "Leslie Alvarado (Mac)",
    group: "App Dev Team",
    github: "https://github.com/LeslieAlvarado1",
    linkedin: "https://www.linkedin.com/in/lesliealvarado1/",
    email: "lalvarado@appdev.yearup.org",
    nickname: "Leader Leslie",
    imageurl: "img/Avatar_Leslie.jpg",
    gender: "female",
  },
  {
    name: "Maximo Mayo",
    group: "App Dev Team",
    github: "https://github.com/MaximoMayo",
    linkedin: "https://www.linkedin.com/in/maximomayo/",
    email: "mmayo@appdev.yearup.org",
    nickname: "Maximum Mayo",
    imageurl: "img/Avatar_Maximo.jpg",
    gender: "male",
  },
  {
    name: "Moncerrat Lua Salas",
    group: "App Dev Team",
    github: "https://github.com/MoncerratLuaSalas",
    linkedin: "https://www.linkedin.com/in/moncerratluasalas/",
    email: "mluasalas@appdev.yearup.org",
    nickname: "Moncerrat Master",
    imageurl: "img/Avatar_Moncerrat.jpg",
    gender: "female",
  },
  {
    name: "Niran Abdulqader",
    group: "App Dev Team",
    github: "https://github.com/NiranAbdulqader",
    linkedin: "https://www.linkedin.com/in/niranabdulqader/",
    email: "nabdulqader@appdev.yearup.org",
    nickname: "Navigator Niran",
    imageurl: "img/Avatar_Niran.jpg",
    gender: "female",
  },
  {
    name: "Rene Banuelos",
    group: "App Dev Team",
    github: "https://github.com/ReneBA1999",
    linkedin: "https://www.linkedin.com/in/renebanuelos/",
    email: "rbanuelos@appdev.yearup.org",
    nickname: "Rene the Reliable",
    imageurl: "img/Avatar_Rene.jpg",
    gender: "male",
  },
  {
    name: "Sabrina Robles",
    group: "App Dev Team",
    github: "https://github.com/SabrinaRobles",
    linkedin: "https://www.linkedin.com/in/sabrinarobles/",
    email: "srobles@appdev.yearup.org",
    nickname: "Sabrina the Synthesizer",
    imageurl: "img/Avatar_Sabrina.jpg",
    gender: "female",
  },
  {
    name: "Uriel Delgado",
    group: "App Dev Team",
    github: "https://github.com/UrielDelgado",
    linkedin: "https://www.linkedin.com/in/uriel-delgado/",
    email: "udelgado@appdev.yearup.org",
    nickname: "Ultra Uriel",
    imageurl: "img/Avatar_Uriel.jpg",
    gender: "male",
  },
  {
    name: "Victor Castaneda",
    group: "App Dev Team",
    github: "https://github.com/Victor-Castaneda",
    linkedin: "https://www.linkedin.com/in/victor-castaneda/",
    email: "vcastaneda@appdev.yearup.org",
    nickname: "Victorious Victor",
    imageurl: "img/Avatar_Victor.jpg",
    gender: "male",
  },
  {
    name: "Remsey Mailjard",
    group: "IT Solutions Group",
    github: "https://github.com/RemseyMailjard",
    linkedin: "https://www.linkedin.com/in/remseymailjard/",
    email: "remsey@skills4-it.nl",
    nickname: "Mailjard the Magnificent",
    imageurl: "img/Avatar_Remsey.jpg",
    gender: "male",
  },
];
